/*
 * This file is generated by jOOQ.
 */
package ch.rasc.hashupgrade.db.tables.pojos;

import java.io.Serializable;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUser implements Serializable {

  private static final long serialVersionUID = 1L;

  private Long id;
  private String userName;
  private String email;
  private String passwordHash;

  public AppUser() {
  }

  public AppUser(AppUser value) {
    this.id = value.id;
    this.userName = value.userName;
    this.email = value.email;
    this.passwordHash = value.passwordHash;
  }

  public AppUser(Long id, String userName, String email, String passwordHash) {
    this.id = id;
    this.userName = userName;
    this.email = email;
    this.passwordHash = passwordHash;
  }

  /**
   * Getter for <code>app_user.id</code>.
   */
  public Long getId() {
    return this.id;
  }

  /**
   * Setter for <code>app_user.id</code>.
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * Getter for <code>app_user.user_name</code>.
   */
  public String getUserName() {
    return this.userName;
  }

  /**
   * Setter for <code>app_user.user_name</code>.
   */
  public void setUserName(String userName) {
    this.userName = userName;
  }

  /**
   * Getter for <code>app_user.email</code>.
   */
  public String getEmail() {
    return this.email;
  }

  /**
   * Setter for <code>app_user.email</code>.
   */
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * Getter for <code>app_user.password_hash</code>.
   */
  public String getPasswordHash() {
    return this.passwordHash;
  }

  /**
   * Setter for <code>app_user.password_hash</code>.
   */
  public void setPasswordHash(String passwordHash) {
    this.passwordHash = passwordHash;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    final AppUser other = (AppUser) obj;
    if (this.id == null) {
      if (other.id != null)
        return false;
    }
    else if (!this.id.equals(other.id))
      return false;
    if (this.userName == null) {
      if (other.userName != null)
        return false;
    }
    else if (!this.userName.equals(other.userName))
      return false;
    if (this.email == null) {
      if (other.email != null)
        return false;
    }
    else if (!this.email.equals(other.email))
      return false;
    if (this.passwordHash == null) {
      if (other.passwordHash != null)
        return false;
    }
    else if (!this.passwordHash.equals(other.passwordHash))
      return false;
    return true;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
    result = prime * result + ((this.userName == null) ? 0 : this.userName.hashCode());
    result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
    result = prime * result
        + ((this.passwordHash == null) ? 0 : this.passwordHash.hashCode());
    return result;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AppUser (");

    sb.append(id);
    sb.append(", ").append(userName);
    sb.append(", ").append(email);
    sb.append(", ").append(passwordHash);

    sb.append(")");
    return sb.toString();
  }
}
