/*
 * This file is generated by jOOQ.
 */
package ch.rasc.hashupgrade.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUser implements Serializable {

    private static final long serialVersionUID = 1338829282;

    private Long   id;
    private String userName;
    private String email;
    private String passwordHash;

    public AppUser() {}

    public AppUser(AppUser value) {
        this.id = value.id;
        this.userName = value.userName;
        this.email = value.email;
        this.passwordHash = value.passwordHash;
    }

    public AppUser(
        Long   id,
        String userName,
        String email,
        String passwordHash
    ) {
        this.id = id;
        this.userName = userName;
        this.email = email;
        this.passwordHash = passwordHash;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPasswordHash() {
        return this.passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
          return true;
        }
        if (obj == null) {
          return false;
        }
        if (getClass() != obj.getClass()) {
          return false;
        }
        final AppUser other = (AppUser) obj;
        if (this.id == null) {
            if (other.id != null) {
              return false;
            }
        }
        else if (!this.id.equals(other.id)) {
          return false;
        }
        if (this.userName == null) {
            if (other.userName != null) {
              return false;
            }
        }
        else if (!this.userName.equals(other.userName)) {
          return false;
        }
        if (this.email == null) {
            if (other.email != null) {
              return false;
            }
        }
        else if (!this.email.equals(other.email)) {
          return false;
        }
        if (this.passwordHash == null) {
            if (other.passwordHash != null) {
              return false;
            }
        }
        else if (!this.passwordHash.equals(other.passwordHash)) {
          return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (this.id == null ? 0 : this.id.hashCode());
        result = prime * result + (this.userName == null ? 0 : this.userName.hashCode());
        result = prime * result + (this.email == null ? 0 : this.email.hashCode());
        result = prime * result + (this.passwordHash == null ? 0 : this.passwordHash.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AppUser (");

        sb.append(this.id);
        sb.append(", ").append(this.userName);
        sb.append(", ").append(this.email);
        sb.append(", ").append(this.passwordHash);

        sb.append(")");
        return sb.toString();
    }
}
