/*
 * This file is generated by jOOQ.
 */
package ch.rasc.hashupgrade.db;

import ch.rasc.hashupgrade.db.tables.AppUser;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

  private static final long serialVersionUID = 1L;

  /**
   * The reference instance of <code>DEFAULT_SCHEMA</code>
   */
  public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

  /**
   * The table <code>app_user</code>.
   */
  public final AppUser APP_USER = AppUser.APP_USER;

  /**
   * No further instances allowed
   */
  private DefaultSchema() {
    super("", null);
  }

  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    return Arrays.asList(AppUser.APP_USER);
  }
}
