/*
 * This file is generated by jOOQ.
 */
package ch.rasc.hashupgrade.db;


import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ch.rasc.hashupgrade.db.tables.AppUser;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONSTRAINT_INDEX_7 = Indexes0.CONSTRAINT_INDEX_7;
    public static final Index CONSTRAINT_INDEX_76 = Indexes0.CONSTRAINT_INDEX_76;
    public static final Index PRIMARY_KEY_7 = Indexes0.PRIMARY_KEY_7;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONSTRAINT_INDEX_7 = Internal.createIndex("CONSTRAINT_INDEX_7", AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.USER_NAME }, true);
        public static Index CONSTRAINT_INDEX_76 = Internal.createIndex("CONSTRAINT_INDEX_76", AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.EMAIL }, true);
        public static Index PRIMARY_KEY_7 = Internal.createIndex("PRIMARY_KEY_7", AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.ID }, true);
    }
}
