/*
 * This file is generated by jOOQ.
 */
package ch.rasc.hashupgrade.db;


import javax.annotation.processing.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ch.rasc.hashupgrade.db.tables.AppUser;
import ch.rasc.hashupgrade.db.tables.records.AppUserRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AppUserRecord, Long> IDENTITY_APP_USER = Identities0.IDENTITY_APP_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppUserRecord> CONSTRAINT_760 = UniqueKeys0.CONSTRAINT_760;
    public static final UniqueKey<AppUserRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
    public static final UniqueKey<AppUserRecord> CONSTRAINT_76 = UniqueKeys0.CONSTRAINT_76;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AppUserRecord, Long> IDENTITY_APP_USER = Internal.createIdentity(AppUser.APP_USER, AppUser.APP_USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AppUserRecord> CONSTRAINT_760 = Internal.createUniqueKey(AppUser.APP_USER, "CONSTRAINT_760", AppUser.APP_USER.ID);
        public static final UniqueKey<AppUserRecord> CONSTRAINT_7 = Internal.createUniqueKey(AppUser.APP_USER, "CONSTRAINT_7", AppUser.APP_USER.USER_NAME);
        public static final UniqueKey<AppUserRecord> CONSTRAINT_76 = Internal.createUniqueKey(AppUser.APP_USER, "CONSTRAINT_76", AppUser.APP_USER.EMAIL);
    }
}
