/*
 * This file is generated by jOOQ.
 */
package ch.rasc.hashupgrade.db;


import javax.annotation.processing.Generated;

import ch.rasc.hashupgrade.db.tables.AppUser;


/**
 * Convenience access to all tables in
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>APP_USER</code>.
     */
    public static final AppUser APP_USER = AppUser.APP_USER;
}
