/*
 * This file is generated by jOOQ.
 */
package ch.rasc.hashupgrade.db;

import ch.rasc.hashupgrade.db.tables.AppUser;

/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

  /**
   * The table <code>app_user</code>.
   */
  public static final AppUser APP_USER = AppUser.APP_USER;
}
