/*
 * This file is generated by jOOQ.
 */
package ch.rasc.hashupgrade.db.tables.records;

import ch.rasc.hashupgrade.db.tables.AppUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord>
    implements Record4<Long, String, String, String> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>app_user.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>app_user.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>app_user.user_name</code>.
   */
  public void setUserName(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>app_user.user_name</code>.
   */
  public String getUserName() {
    return (String) get(1);
  }

  /**
   * Setter for <code>app_user.email</code>.
   */
  public void setEmail(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>app_user.email</code>.
   */
  public String getEmail() {
    return (String) get(2);
  }

  /**
   * Setter for <code>app_user.password_hash</code>.
   */
  public void setPasswordHash(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>app_user.password_hash</code>.
   */
  public String getPasswordHash() {
    return (String) get(3);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record4 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row4<Long, String, String, String> fieldsRow() {
    return (Row4) super.fieldsRow();
  }

  @Override
  public Row4<Long, String, String, String> valuesRow() {
    return (Row4) super.valuesRow();
  }

  @Override
  public Field<Long> field1() {
    return AppUser.APP_USER.ID;
  }

  @Override
  public Field<String> field2() {
    return AppUser.APP_USER.USER_NAME;
  }

  @Override
  public Field<String> field3() {
    return AppUser.APP_USER.EMAIL;
  }

  @Override
  public Field<String> field4() {
    return AppUser.APP_USER.PASSWORD_HASH;
  }

  @Override
  public Long component1() {
    return getId();
  }

  @Override
  public String component2() {
    return getUserName();
  }

  @Override
  public String component3() {
    return getEmail();
  }

  @Override
  public String component4() {
    return getPasswordHash();
  }

  @Override
  public Long value1() {
    return getId();
  }

  @Override
  public String value2() {
    return getUserName();
  }

  @Override
  public String value3() {
    return getEmail();
  }

  @Override
  public String value4() {
    return getPasswordHash();
  }

  @Override
  public AppUserRecord value1(Long value) {
    setId(value);
    return this;
  }

  @Override
  public AppUserRecord value2(String value) {
    setUserName(value);
    return this;
  }

  @Override
  public AppUserRecord value3(String value) {
    setEmail(value);
    return this;
  }

  @Override
  public AppUserRecord value4(String value) {
    setPasswordHash(value);
    return this;
  }

  @Override
  public AppUserRecord values(Long value1, String value2, String value3, String value4) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached AppUserRecord
   */
  public AppUserRecord() {
    super(AppUser.APP_USER);
  }

  /**
   * Create a detached, initialised AppUserRecord
   */
  public AppUserRecord(Long id, String userName, String email, String passwordHash) {
    super(AppUser.APP_USER);

    setId(id);
    setUserName(userName);
    setEmail(email);
    setPasswordHash(passwordHash);
  }

  /**
   * Create a detached, initialised AppUserRecord
   */
  public AppUserRecord(ch.rasc.hashupgrade.db.tables.pojos.AppUser value) {
    super(AppUser.APP_USER);

    if (value != null) {
      setId(value.getId());
      setUserName(value.getUserName());
      setEmail(value.getEmail());
      setPasswordHash(value.getPasswordHash());
    }
  }
}
